version: "3.8"

services:
  web:
    container_name: app
    build:
      context: "."
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    env_file:
      - .env
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: gunicorn "app:create_app()" -c gunicorn.py

  celery-worker:
    container_name: worker
    build:
      context: "."
    env_file:
      - .env
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: celery -A app.clr worker -l info -c 4

  celery-beat:
    container_name: beat
    build:
      context: "."
    env_file:
      - .env
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: celery -A app.timer beat -l info -s /tmp/celerybeat-schedule

